name: Go Build and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build and Package
      run: |
        GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o bootstrap main.go
        zip trimana-dashboard-api.zip bootstrap

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: zip-file
        path: trimana-dashboard-api.zip

  upload:
    runs-on: ubuntu-latest

    needs: build  # This ensures the 'build' job is completed before starting this job

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: zip-file

    - name: Copy files to the test-prod S3 bucket
      run: |
        aws s3 cp trimana-dashboard-api.zip s3://trimana-dashboard-bucket/lambdas/trimana-dashboard-api.zip
