name: Go Build and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o bootstrap main.go
      run: zip trimana-dashboard-api.zip bootstrap

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Copy files to the test-prod S3 bucket
      run: |
        aws s3 cp trimana-dashboard-api.zip s3://trimana-dashboard-bucket/lambdas/trimana-dashboard-api.zip